/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import program.Program;
import db.Database;
import java.util.logging.Level;
import java.util.logging.Logger;
import oru.inf.InfException;
import java.time.LocalDate;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.*;

/**
 *
 * @author Sara
 */
public class MainApp extends javax.swing.JFrame {

    private String datum;
    private final Program program;
    
    //Ska tas bort sen
    private static final String NAME = "mibdb";
    private static final String PORT = "3306";
    private static final String USER = "mibdba";
    private static final String PASSWORD = "mibkey";
    
    private final InfDB idb;
    //Ska tas bort sen
    
    /**
     * Creates new form MainApp
     * @throws oru.inf.InfException
     */
    public MainApp() throws InfException {
        program = new Program(new Database());
        program.printAllAgents();
        
        //Ska bort
        idb = new InfDB(NAME, PORT, USER, PASSWORD);
        //Ska bort
        
        initComponents();
        
    }
    
    private void fyllAgenter()
    {
        List<String> allAgents = program.getAllAgents();
        for(String oneAgent : allAgents){
            System.out.println(oneAgent);
            jAnsvarigBox.addItem(oneAgent);
        }
    }
    
    private void fyllPlatser()
    {
        List<String> allPlatser = program.getAllPlatser();
        for(String onePlats : allPlatser){
            System.out.println(onePlats);
            jPlatsBox.addItem(onePlats);
        }
    }
    /*
    private void fyllAnsvarigRoller() {
        try {
            int id = 1;
            String cont = idb.fetchSingle("SELECT count(namn) FROM Agent");
            int max = Integer.parseInt(cont);
            while (id <= max) {
                String namn = idb.fetchSingle("SELECT Namn FROM Agent WHERE Agent_ID=" + id);
                jAnsvarigBox.addItem(namn);
                id++;
            }
        } catch (Exception e) {
            System.out.println("Knas!");
        }
    }
    */

    //Lägger in automatiskt dagens datum i datumfältet i gränssnittet
    //Detta ska ändras så att man kan välja datum men det måste vara denna typ (YY-MM-DD)
    private void sattDatum() {
        LocalDate date = LocalDate.now();
        String datum = date.toString();
        this.datum = datum;
        datumField.setText(datum);
    }

    //Samma funktion som fyllAnsvarigRoller-metoden fast den fyller PLATS i gränssnittet
    /*private void fyllPlatser() {
        try {
            int id = 1;
            String cont = idb.fetchSingle("SELECT count(Benamning) FROM Plats");
            int max = Integer.parseInt(cont);
            while (id <= max) {
                String plats = idb.fetchSingle("SELECT Benamning FROM Plats WHERE Plats_ID=" + id);
                jPlatsBox.addItem(plats);
                id++;
            }

        } catch (Exception e) {
            System.err.println("Knas");
        }
    }
    */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        txtNewPass = new javax.swing.JTextField();
        lblNewPass = new javax.swing.JLabel();
        btnApprove = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        panelLogin = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        txtPassword = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        panelHome = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();
        scrollPaneAliens = new javax.swing.JScrollPane();
        listAliens = new javax.swing.JList<>();
        lblAlien = new javax.swing.JLabel();
        btnDeleteAlien = new javax.swing.JButton();
        btnRegAlien = new javax.swing.JButton();
        btnUpdateAlien = new javax.swing.JButton();
        scrollPaneAgents = new javax.swing.JScrollPane();
        listAgents = new javax.swing.JList<>();
        lblAlien1 = new javax.swing.JLabel();
        btnRegAgent = new javax.swing.JButton();
        btnUpdateAgent = new javax.swing.JButton();
        btnDeleteAgent = new javax.swing.JButton();
        lblAgentPhone = new javax.swing.JLabel();
        lblAgentName = new javax.swing.JLabel();
        lblAgentPhone1 = new javax.swing.JLabel();
        lblAgentPhone2 = new javax.swing.JLabel();
        scrollPaneUtrustning = new javax.swing.JScrollPane();
        listUtrustning = new javax.swing.JList<>();
        lblUtrustning = new javax.swing.JLabel();
        btnDeleteUtrustning = new javax.swing.JButton();
        panelRegAlien = new javax.swing.JPanel();
        datumLabel = new javax.swing.JLabel();
        namnLabel = new javax.swing.JLabel();
        ansvLabel = new javax.swing.JLabel();
        tfnField1 = new javax.swing.JTextField();
        jAlienID = new javax.swing.JSpinner();
        namnField = new javax.swing.JTextField();
        teleLabel = new javax.swing.JLabel();
        jPlatsBox = new javax.swing.JComboBox<>();
        harRegRubrik = new javax.swing.JLabel();
        platsLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bRegistrera = new javax.swing.JButton();
        datumField = new javax.swing.JTextField();
        losenField = new javax.swing.JTextField();
        losenLabel = new javax.swing.JLabel();
        jAnsvarigBox = new javax.swing.JComboBox<>();
        regAliRubrik = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panelUpdateAgent = new javax.swing.JPanel();
        btnBackToHome = new javax.swing.JButton();
        lblUpdateAgent = new javax.swing.JLabel();
        panelUpdateAlien = new javax.swing.JPanel();
        btnBackToHome1 = new javax.swing.JButton();
        lblUpdateAlien = new javax.swing.JLabel();
        panelRegAgent = new javax.swing.JPanel();
        datumLabel1 = new javax.swing.JLabel();
        namnLabel1 = new javax.swing.JLabel();
        lblOmrade = new javax.swing.JLabel();
        txtAgentPhone = new javax.swing.JTextField();
        jAgentID = new javax.swing.JSpinner();
        txtAgentName = new javax.swing.JTextField();
        teleLabel1 = new javax.swing.JLabel();
        harRegRubrik1 = new javax.swing.JLabel();
        platsLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRegNewAgent = new javax.swing.JButton();
        txtAgentReg = new javax.swing.JTextField();
        txtAgentPassword = new javax.swing.JTextField();
        losenLabel1 = new javax.swing.JLabel();
        jOmradeBox = new javax.swing.JComboBox<>();
        regAliRubrik1 = new javax.swing.JLabel();
        btnRegAgentBack = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        panelAlienHome = new javax.swing.JPanel();
        btnChangeAlienPassword = new javax.swing.JButton();
        lblUserAlien = new javax.swing.JLabel();
        btnLogoutAlien = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblAlienAgentValue = new javax.swing.JLabel();
        panelAgentHome = new javax.swing.JPanel();
        lblUser1 = new javax.swing.JLabel();
        btnLogout1 = new javax.swing.JButton();
        btnChangePassword1 = new javax.swing.JButton();
        scrollPaneAliens1 = new javax.swing.JScrollPane();
        listAliens1 = new javax.swing.JList<>();
        lblAlien2 = new javax.swing.JLabel();
        btnRegAlien1 = new javax.swing.JButton();
        btnUpdateAlien1 = new javax.swing.JButton();
        btnRegUtrust = new javax.swing.JButton();
        btnShowInfo = new javax.swing.JButton();
        scrollPaneUtrustning1 = new javax.swing.JScrollPane();
        listUtrustning1 = new javax.swing.JList<>();
        lblUtrustning1 = new javax.swing.JLabel();
        btnDeleteUtrustning1 = new javax.swing.JButton();
        scrollPaneAliens2 = new javax.swing.JScrollPane();
        listAliens2 = new javax.swing.JList<>();
        scrollPaneAliens3 = new javax.swing.JScrollPane();
        listAliens3 = new javax.swing.JList<>();
        lblAlien3 = new javax.swing.JLabel();
        lblAlien4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        lblAlien5 = new javax.swing.JLabel();
        lblAlien6 = new javax.swing.JLabel();
        lblAlien7 = new javax.swing.JLabel();
        lblAlien8 = new javax.swing.JLabel();

        jDialog1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog1.setTitle("Byt lösenord");

        txtNewPass.setText("jTextField3");

        lblNewPass.setText("Nytt lösenord:");

        btnApprove.setText("Godkänn");

        btnBack.setText("Tillbaka");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNewPass)
                    .addComponent(txtNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnApprove)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(34, 34, 34))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(lblNewPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApprove)
                    .addComponent(btnBack))
                .addGap(20, 20, 20))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 400));

        panelLogin.setMaximumSize(new java.awt.Dimension(600, 400));
        panelLogin.setMinimumSize(new java.awt.Dimension(600, 400));
        panelLogin.setPreferredSize(new java.awt.Dimension(600, 400));
        panelLogin.setRequestFocusEnabled(false);

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginLayout.createSequentialGroup()
                        .addComponent(btnLogin)
                        .addGap(30, 30, 30)))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnLogin)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        panelHome.setMaximumSize(new java.awt.Dimension(600, 400));
        panelHome.setMinimumSize(new java.awt.Dimension(600, 400));
        panelHome.setPreferredSize(new java.awt.Dimension(600, 400));

        lblUser.setText("hello");

        btnLogout.setText("Logga ut");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnChangePassword.setText("Ändra lösenord");
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });

        listAliens.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollPaneAliens.setViewportView(listAliens);

        lblAlien.setText("Aliens");

        btnDeleteAlien.setText("Ta bort");

        btnRegAlien.setText("Registrera");
        btnRegAlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegAlienActionPerformed(evt);
            }
        });

        btnUpdateAlien.setText("Ändra");
        btnUpdateAlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateAlienActionPerformed(evt);
            }
        });

        listAgents.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollPaneAgents.setViewportView(listAgents);

        lblAlien1.setText("Agenter");

        btnRegAgent.setText("Registrera");
        btnRegAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegAgentActionPerformed(evt);
            }
        });

        btnUpdateAgent.setText("Ändra");
        btnUpdateAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateAgentActionPerformed(evt);
            }
        });

        btnDeleteAgent.setText("Ta bort");

        lblAgentPhone.setText("Telefon");

        lblAgentName.setText("Namn");

        lblAgentPhone1.setText("Datum");

        lblAgentPhone2.setText("Område");

        listUtrustning.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollPaneUtrustning.setViewportView(listUtrustning);

        lblUtrustning.setText("Utrustning");

        btnDeleteUtrustning.setText("Ta bort");

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(scrollPaneAliens, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(scrollPaneUtrustning, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelHomeLayout.createSequentialGroup()
                            .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblUtrustning)
                                .addGroup(panelHomeLayout.createSequentialGroup()
                                    .addComponent(btnDeleteAlien)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnUpdateAlien)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnRegAlien)))
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(lblAlien))
                    .addComponent(btnDeleteUtrustning))
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(scrollPaneAgents, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAgentPhone)
                                    .addGroup(panelHomeLayout.createSequentialGroup()
                                        .addComponent(btnDeleteAgent)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnUpdateAgent)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRegAgent))
                                    .addComponent(lblAgentName)
                                    .addComponent(lblAgentPhone1)
                                    .addComponent(lblAgentPhone2)))
                            .addGroup(panelHomeLayout.createSequentialGroup()
                                .addComponent(lblUser)
                                .addGap(18, 18, 18)
                                .addComponent(btnLogout)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnChangePassword)))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHomeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAlien1)
                        .addGap(125, 125, 125))))
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAlien)
                    .addComponent(lblAlien1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollPaneAliens, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollPaneAgents, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteAlien)
                    .addComponent(btnRegAlien)
                    .addComponent(btnUpdateAlien)
                    .addComponent(btnRegAgent)
                    .addComponent(btnDeleteAgent)
                    .addComponent(btnUpdateAgent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAgentName)
                    .addComponent(lblUtrustning, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addComponent(scrollPaneUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteUtrustning))
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addComponent(lblAgentPhone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAgentPhone1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAgentPhone2)
                        .addGap(45, 45, 45)
                        .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLogout)
                            .addComponent(btnChangePassword)
                            .addComponent(lblUser))))
                .addGap(63, 63, 63))
        );

        panelRegAlien.setMaximumSize(new java.awt.Dimension(600, 400));
        panelRegAlien.setMinimumSize(new java.awt.Dimension(600, 400));
        panelRegAlien.setPreferredSize(new java.awt.Dimension(600, 400));

        datumLabel.setText("Datum:");

        namnLabel.setText("Namn:");

        ansvLabel.setText("Ansvarig:");

        tfnField1.setColumns(7);
        tfnField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnField1ActionPerformed(evt);
            }
        });

        jAlienID.setToolTipText("ID får inte vara identiskt med ett annat Alien_ID i databasen");
        jAlienID.setValue(4);
        jAlienID.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jAlienIDStateChanged(evt);
            }
        });

        namnField.setColumns(7);
        namnField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namnFieldActionPerformed(evt);
            }
        });

        teleLabel.setText("Telefon");

        platsLabel.setText("Plats:");

        jLabel1.setText("Alien_ID");

        bRegistrera.setText("Registrera");
        bRegistrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistreraActionPerformed(evt);
            }
        });

        datumField.setColumns(7);
        datumField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datumFieldActionPerformed(evt);
            }
        });

        losenField.setColumns(7);
        losenField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                losenFieldActionPerformed(evt);
            }
        });

        losenLabel.setText("Lösenord:");

        jAnsvarigBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAnsvarigBoxActionPerformed(evt);
            }
        });

        regAliRubrik.setFont(new java.awt.Font("Cambay Devanagari", 1, 24)); // NOI18N
        regAliRubrik.setText("Registrera alien");

        jButton1.setText("Tillbaka");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRegAlienLayout = new javax.swing.GroupLayout(panelRegAlien);
        panelRegAlien.setLayout(panelRegAlienLayout);
        panelRegAlienLayout.setHorizontalGroup(
            panelRegAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegAlienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRegAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegAlienLayout.createSequentialGroup()
                        .addComponent(jPlatsBox, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelRegAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRegAlienLayout.createSequentialGroup()
                                .addComponent(losenField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jAnsvarigBox, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bRegistrera, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelRegAlienLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addGroup(panelRegAlienLayout.createSequentialGroup()
                        .addGroup(panelRegAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelRegAlienLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(panelRegAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(datumLabel)
                                    .addComponent(platsLabel))
                                .addGap(71, 71, 71))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegAlienLayout.createSequentialGroup()
                                .addGroup(panelRegAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jAlienID, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(datumField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)))
                        .addGroup(panelRegAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegAlienLayout.createSequentialGroup()
                                .addComponent(namnLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelRegAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ansvLabel)
                                    .addComponent(teleLabel)
                                    .addComponent(tfnField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegAlienLayout.createSequentialGroup()
                                .addGroup(panelRegAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namnField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(losenLabel))
                                .addGap(112, 112, 112))))
                    .addGroup(panelRegAlienLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(regAliRubrik))
                    .addGroup(panelRegAlienLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(harRegRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addGap(266, 266, 266))
        );
        panelRegAlienLayout.setVerticalGroup(
            panelRegAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegAlienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(regAliRubrik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAlienID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datumLabel)
                    .addComponent(namnLabel)
                    .addComponent(teleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfnField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(platsLabel)
                    .addComponent(losenLabel)
                    .addComponent(ansvLabel))
                .addGap(4, 4, 4)
                .addGroup(panelRegAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(losenField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAnsvarigBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPlatsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bRegistrera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(harRegRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addContainerGap())
        );

        panelUpdateAgent.setMaximumSize(new java.awt.Dimension(600, 400));
        panelUpdateAgent.setMinimumSize(new java.awt.Dimension(600, 400));
        panelUpdateAgent.setPreferredSize(new java.awt.Dimension(600, 400));

        btnBackToHome.setText("Tillbaka");
        btnBackToHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToHomeActionPerformed(evt);
            }
        });

        lblUpdateAgent.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUpdateAgent.setText("Ändra Agent");

        javax.swing.GroupLayout panelUpdateAgentLayout = new javax.swing.GroupLayout(panelUpdateAgent);
        panelUpdateAgent.setLayout(panelUpdateAgentLayout);
        panelUpdateAgentLayout.setHorizontalGroup(
            panelUpdateAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUpdateAgentLayout.createSequentialGroup()
                .addContainerGap(257, Short.MAX_VALUE)
                .addComponent(lblUpdateAgent)
                .addGap(240, 240, 240))
            .addGroup(panelUpdateAgentLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnBackToHome)
                .addContainerGap())
        );
        panelUpdateAgentLayout.setVerticalGroup(
            panelUpdateAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUpdateAgentLayout.createSequentialGroup()
                .addComponent(lblUpdateAgent)
                .addGap(224, 224, 224)
                .addComponent(btnBackToHome)
                .addGap(128, 128, 128))
        );

        panelUpdateAlien.setMaximumSize(new java.awt.Dimension(600, 400));
        panelUpdateAlien.setMinimumSize(new java.awt.Dimension(600, 400));

        btnBackToHome1.setText("Tillbaka");
        btnBackToHome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToHome1ActionPerformed(evt);
            }
        });

        lblUpdateAlien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUpdateAlien.setText("Ändra Alien");

        javax.swing.GroupLayout panelUpdateAlienLayout = new javax.swing.GroupLayout(panelUpdateAlien);
        panelUpdateAlien.setLayout(panelUpdateAlienLayout);
        panelUpdateAlienLayout.setHorizontalGroup(
            panelUpdateAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUpdateAlienLayout.createSequentialGroup()
                .addContainerGap(265, Short.MAX_VALUE)
                .addComponent(lblUpdateAlien)
                .addGap(240, 240, 240))
            .addGroup(panelUpdateAlienLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnBackToHome1)
                .addContainerGap())
        );
        panelUpdateAlienLayout.setVerticalGroup(
            panelUpdateAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUpdateAlienLayout.createSequentialGroup()
                .addComponent(lblUpdateAlien)
                .addGap(224, 224, 224)
                .addComponent(btnBackToHome1)
                .addGap(128, 128, 128))
        );

        panelRegAgent.setMaximumSize(new java.awt.Dimension(600, 400));
        panelRegAgent.setMinimumSize(new java.awt.Dimension(600, 400));

        datumLabel1.setText("Datum:");

        namnLabel1.setText("Namn:");

        lblOmrade.setText("Område:");

        txtAgentPhone.setColumns(7);
        txtAgentPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgentPhoneActionPerformed(evt);
            }
        });

        jAgentID.setToolTipText("ID får inte vara identiskt med ett annat Alien_ID i databasen");
        jAgentID.setValue(4);
        jAgentID.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jAgentIDStateChanged(evt);
            }
        });

        txtAgentName.setColumns(7);
        txtAgentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgentNameActionPerformed(evt);
            }
        });

        teleLabel1.setText("Telefon");

        platsLabel1.setText("Administratör:");

        jLabel2.setText("Agent_ID");

        btnRegNewAgent.setText("Registrera");
        btnRegNewAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegNewAgentActionPerformed(evt);
            }
        });

        txtAgentReg.setColumns(7);
        txtAgentReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgentRegActionPerformed(evt);
            }
        });

        txtAgentPassword.setColumns(7);
        txtAgentPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgentPasswordActionPerformed(evt);
            }
        });

        losenLabel1.setText("Lösenord:");

        jOmradeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOmradeBoxActionPerformed(evt);
            }
        });

        regAliRubrik1.setFont(new java.awt.Font("Cambay Devanagari", 1, 24)); // NOI18N
        regAliRubrik1.setText("Registrera agent");

        btnRegAgentBack.setText("Tillbaka");
        btnRegAgentBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegAgentBackActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Ja");

        javax.swing.GroupLayout panelRegAgentLayout = new javax.swing.GroupLayout(panelRegAgent);
        panelRegAgent.setLayout(panelRegAgentLayout);
        panelRegAgentLayout.setHorizontalGroup(
            panelRegAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegAgentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRegAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegAgentLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(regAliRubrik1))
                    .addComponent(btnRegAgentBack)
                    .addGroup(panelRegAgentLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panelRegAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jAgentID, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(panelRegAgentLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(panelRegAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panelRegAgentLayout.createSequentialGroup()
                                .addGroup(panelRegAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(datumLabel1)
                                    .addComponent(platsLabel1)
                                    .addGroup(panelRegAgentLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(txtAgentReg, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(39, 39, 39)
                                .addGroup(panelRegAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegAgentLayout.createSequentialGroup()
                                        .addComponent(namnLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(panelRegAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblOmrade)
                                            .addComponent(teleLabel1)
                                            .addComponent(txtAgentPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegAgentLayout.createSequentialGroup()
                                        .addGroup(panelRegAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAgentName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(losenLabel1)
                                            .addComponent(txtAgentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnRegNewAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(112, 112, 112))))
                            .addGroup(panelRegAgentLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelRegAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelRegAgentLayout.createSequentialGroup()
                                        .addGap(137, 137, 137)
                                        .addComponent(jOmradeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(harRegRubrik1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(266, 266, 266))
        );
        panelRegAgentLayout.setVerticalGroup(
            panelRegAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegAgentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(regAliRubrik1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAgentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datumLabel1)
                    .addComponent(namnLabel1)
                    .addComponent(teleLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAgentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAgentPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAgentReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(platsLabel1)
                    .addComponent(losenLabel1)
                    .addComponent(lblOmrade))
                .addGap(5, 5, 5)
                .addGroup(panelRegAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAgentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jOmradeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addGap(18, 18, 18)
                .addComponent(btnRegNewAgent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(harRegRubrik1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnRegAgentBack)
                .addContainerGap())
        );

        panelAlienHome.setMaximumSize(new java.awt.Dimension(600, 400));
        panelAlienHome.setMinimumSize(new java.awt.Dimension(600, 400));

        btnChangeAlienPassword.setText("Ändra lösenord");
        btnChangeAlienPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeAlienPasswordActionPerformed(evt);
            }
        });

        lblUserAlien.setText("hello");

        btnLogoutAlien.setText("Logga ut");
        btnLogoutAlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutAlienActionPerformed(evt);
            }
        });

        jLabel3.setText("Ansvarig Agent: ");

        lblAlienAgentValue.setText("Agentname");

        javax.swing.GroupLayout panelAlienHomeLayout = new javax.swing.GroupLayout(panelAlienHome);
        panelAlienHome.setLayout(panelAlienHomeLayout);
        panelAlienHomeLayout.setHorizontalGroup(
            panelAlienHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlienHomeLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(lblUserAlien)
                .addGap(60, 60, 60)
                .addGroup(panelAlienHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAlienHomeLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAlienAgentValue))
                    .addGroup(panelAlienHomeLayout.createSequentialGroup()
                        .addComponent(btnLogoutAlien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnChangeAlienPassword)))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        panelAlienHomeLayout.setVerticalGroup(
            panelAlienHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAlienHomeLayout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addGroup(panelAlienHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblAlienAgentValue))
                .addGap(81, 81, 81)
                .addGroup(panelAlienHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogoutAlien)
                    .addComponent(btnChangeAlienPassword)
                    .addComponent(lblUserAlien))
                .addGap(160, 160, 160))
        );

        panelAgentHome.setMaximumSize(new java.awt.Dimension(600, 400));
        panelAgentHome.setMinimumSize(new java.awt.Dimension(600, 400));

        lblUser1.setText("hello");

        btnLogout1.setText("Logga ut");
        btnLogout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogout1ActionPerformed(evt);
            }
        });

        btnChangePassword1.setText("Ändra lösenord");
        btnChangePassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassword1ActionPerformed(evt);
            }
        });

        listAliens1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollPaneAliens1.setViewportView(listAliens1);

        lblAlien2.setText("Aliens");

        btnRegAlien1.setText("Registrera");
        btnRegAlien1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegAlien1ActionPerformed(evt);
            }
        });

        btnUpdateAlien1.setText("Ändra");
        btnUpdateAlien1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateAlien1ActionPerformed(evt);
            }
        });

        btnRegUtrust.setText("Registrera");
        btnRegUtrust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegUtrustActionPerformed(evt);
            }
        });

        btnShowInfo.setText("Visa info");
        btnShowInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowInfoActionPerformed(evt);
            }
        });

        listUtrustning1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollPaneUtrustning1.setViewportView(listUtrustning1);

        lblUtrustning1.setText("Utrustning");

        btnDeleteUtrustning1.setText("Ta bort");

        listAliens2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollPaneAliens2.setViewportView(listAliens2);

        listAliens3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollPaneAliens3.setViewportView(listAliens3);

        lblAlien3.setText("Område");

        lblAlien4.setText("Ras");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        lblAlien5.setText("Aliens");

        lblAlien6.setText("Reg t.o.m");

        lblAlien7.setText("Reg fr.o.m");

        lblAlien8.setText("chef:");

        javax.swing.GroupLayout panelAgentHomeLayout = new javax.swing.GroupLayout(panelAgentHome);
        panelAgentHome.setLayout(panelAgentHomeLayout);
        panelAgentHomeLayout.setHorizontalGroup(
            panelAgentHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgentHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAgentHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAgentHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(scrollPaneAliens1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(scrollPaneUtrustning1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelAgentHomeLayout.createSequentialGroup()
                            .addGroup(panelAgentHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panelAgentHomeLayout.createSequentialGroup()
                                    .addGap(78, 78, 78)
                                    .addComponent(lblUtrustning1))
                                .addGroup(panelAgentHomeLayout.createSequentialGroup()
                                    .addComponent(btnShowInfo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnUpdateAlien1)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnRegAlien1)))
                    .addGroup(panelAgentHomeLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(lblAlien2))
                    .addGroup(panelAgentHomeLayout.createSequentialGroup()
                        .addComponent(btnDeleteUtrustning1)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegUtrust)))
                .addGroup(panelAgentHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgentHomeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelAgentHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAgentHomeLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblUser1)
                                .addGap(18, 18, 18)
                                .addComponent(btnLogout1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnChangePassword1))
                            .addComponent(lblAlien5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgentHomeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(panelAgentHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgentHomeLayout.createSequentialGroup()
                                .addGroup(panelAgentHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAlien7)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelAgentHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAlien6))
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgentHomeLayout.createSequentialGroup()
                                .addGroup(panelAgentHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgentHomeLayout.createSequentialGroup()
                                        .addComponent(scrollPaneAliens2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(scrollPaneAliens3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelAgentHomeLayout.createSequentialGroup()
                                        .addComponent(lblAlien3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblAlien8)
                                        .addGap(116, 116, 116)
                                        .addComponent(lblAlien4)
                                        .addGap(67, 67, 67)))
                                .addGap(17, 17, 17))))))
        );
        panelAgentHomeLayout.setVerticalGroup(
            panelAgentHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgentHomeLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panelAgentHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAgentHomeLayout.createSequentialGroup()
                        .addComponent(lblAlien2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollPaneAliens1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAgentHomeLayout.createSequentialGroup()
                        .addGroup(panelAgentHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAlien3)
                            .addComponent(lblAlien4)
                            .addComponent(lblAlien8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAgentHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollPaneAliens2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrollPaneAliens3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(panelAgentHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAgentHomeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelAgentHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegAlien1)
                            .addComponent(btnUpdateAlien1)
                            .addComponent(btnShowInfo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblUtrustning1))
                    .addGroup(panelAgentHomeLayout.createSequentialGroup()
                        .addGroup(panelAgentHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAgentHomeLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(lblAlien6))
                            .addGroup(panelAgentHomeLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblAlien7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAgentHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAlien5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAgentHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAgentHomeLayout.createSequentialGroup()
                        .addComponent(scrollPaneUtrustning1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAgentHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDeleteUtrustning1)
                            .addComponent(btnRegUtrust)))
                    .addGroup(panelAgentHomeLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAgentHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLogout1)
                            .addComponent(btnChangePassword1)
                            .addComponent(lblUser1))))
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelRegAlien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(panelUpdateAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelUpdateAlien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(2, 2, 2)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelRegAgent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(panelAlienHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAgentHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(2, 2, 2)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelRegAlien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addComponent(panelUpdateAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelUpdateAlien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(61, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelRegAgent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(61, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addComponent(panelAlienHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelAgentHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(61, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        Integer userId = Integer.valueOf(txtUsername.getText());
        String password = txtPassword.getText();
        
        program.logIn(userId, password);
        
        if(!program.isLoggedIn())
        {
            System.out.println("Could not login!");
            return;
        }
        
        if(program.isLoggedInAsAgent() && program.isAdmin())
        {
            showHome();
        }
        else if(program.isLoggedInAsAgent())
        {
            showAgentHome();
        }
        else if(program.isLoggedInAsAlien())
        {
            showAlienHome();
        }
        else
        {
            //Not logged in at all show error?
        }
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void showAlienHome()
    {
        panelLogin.setVisible(false);
        
        lblAlienAgentValue.setText(program.getAlienContact());
        lblUserAlien.setText(program.getUserName());
        panelAlienHome.setVisible(true);
    }
    
    private void showHome()
    {
        //Disable all other panels
        panelLogin.setVisible(false);
        
        //Show home panel
        lblUser.setText(program.getUserName());
        panelHome.setVisible(true);
    }
    
    private void showAgentHome()
    {
       panelLogin.setVisible(false);
       //hämta alla aliens - prog->databas
       //for a : alist
       // jalienbox1.add(a)
       
       panelAgentHome.setVisible(true);
    }
    
    private void showLogin()
    {
        panelHome.setVisible(false);
        panelLogin.setVisible(true);
        panelAlienHome.setVisible(false);
    }
    
    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        program.logOut();
        showLogin();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void datumFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datumFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datumFieldActionPerformed

    private void namnFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namnFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namnFieldActionPerformed

    private void losenFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_losenFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_losenFieldActionPerformed

    private void tfnField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnField1ActionPerformed

    private void bRegistreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistreraActionPerformed
        // TODO add your handling code here:
        try {
            //Hämtar valt plats ID
            String cont = jPlatsBox.getSelectedItem().toString();
            String platsid = idb.fetchSingle("SELECT Plats_ID FROM Plats WHERE Benamning='" + cont + "'");
            //Omvandlar variabeln platsid till en int
            int plats = Integer.parseInt(platsid);
            //En "check" så att rätt värde visas
            System.out.println("Plats: " + plats);

            //Hämtar inmatat Alien ID
            String cont2 = jAlienID.getValue().toString();
            int aid = Integer.parseInt(cont2);
            System.out.println("Alien ID: " + aid);

            //Hämtar inmatat ansvarig_ID (DATATYPEN MÅSTE VARA AV INT DÄR DATABASENS TYPER ÄR INT)
            String ansvarig = jAnsvarigBox.getSelectedItem().toString();
            String ans1 = idb.fetchSingle("SELECT Agent_ID FROM Agent WHERE Namn ='" + ansvarig + "'");
            int ans = Integer.parseInt(ans1);
            System.out.println("Ansvarig :" + ans);

            //Hämtar datum
            this.datum = datumField.getText();
            System.out.println("Datum: " + datum);

            //Hämtar inmatat lösenord
            String losenord = losenField.getText();
            System.out.println("Lösenord: " + losenord);

            //Hämtar inmatat namn
            String namn = namnField.getText();
            System.out.println("Namn: " + namn);

            //Hämtar telefon
            String telefon = tfnField1.getText();

            //Hämtar alla variabler och lägger till Alien
            try {

                //Kollar så att samtliga rader är inmatade annars error
                if(losenord.isEmpty() || namn.isEmpty() || telefon.isEmpty()){
                    JOptionPane.showMessageDialog(null, "Samtliga fält måste vara ifyllda!");
                }
                else{
                    //Sätter in samtliga värden i databasen och reggar en ny alien
                    idb.insert("INSERT INTO Alien (Alien_ID, Registreringsdatum, Losenord, Namn, Telefon, Plats, Ansvarig_Agent) VALUES ('"
                        + aid + "','"
                        + datum + "','"
                        + losenord + "','"
                        + namn + "','"
                        + telefon + "','"
                        + plats + "','"
                        + ans + "')");
                    //Printas ut under button att alien har reggats
                    harRegRubrik.setText(namn + " har registrerats!");
                }

            } catch (InfException e) {
                JOptionPane.showMessageDialog(null, "Nånting blev fel. Kanske Alien_ID redan finns i databasen?");
            }

        } catch (InfException e) {
            System.out.println("Knas" + e.getMessage());
        }
    }//GEN-LAST:event_bRegistreraActionPerformed

    private void jAnsvarigBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAnsvarigBoxActionPerformed
        // TODO add your handling code here¨
    }//GEN-LAST:event_jAnsvarigBoxActionPerformed

    private void jAlienIDStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jAlienIDStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jAlienIDStateChanged

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        jDialog1.setSize(500, 300);
        jDialog1.setVisible(true);
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void btnRegAlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegAlienActionPerformed
        panelHome.setVisible(false);
        panelLogin.setVisible(false);
        panelRegAlien.setVisible(true);
        panelUpdateAgent.setVisible(false);
        panelRegAgent.setVisible(false);
        panelUpdateAlien.setVisible(false);
    }//GEN-LAST:event_btnRegAlienActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        panelHome.setVisible(true);
        panelLogin.setVisible(false);
        panelRegAlien.setVisible(false);
        panelRegAgent.setVisible(false);
        panelUpdateAgent.setVisible(false);
        panelUpdateAlien.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBackToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToHomeActionPerformed
        panelHome.setVisible(true);
        panelLogin.setVisible(false);
        panelRegAlien.setVisible(false);
        panelRegAgent.setVisible(false);
        panelUpdateAgent.setVisible(false);
        panelUpdateAlien.setVisible(false);
    }//GEN-LAST:event_btnBackToHomeActionPerformed

    private void btnUpdateAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateAgentActionPerformed
        if(listAgents.getSelectedValue() == null)
        {
            //Ingen agent vald
            return;
        }
        updateAgent(listAgents.getSelectedValue());
        
    }//GEN-LAST:event_btnUpdateAgentActionPerformed

    private void btnUpdateAlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateAlienActionPerformed
        if(listAliens.getSelectedValue() == null)
        {
            //Igen alien vald
            return;
        }
        
        panelHome.setVisible(false);
        panelLogin.setVisible(false);
        panelRegAlien.setVisible(false);
        panelUpdateAgent.setVisible(false);
        panelRegAgent.setVisible(false);
        panelUpdateAlien.setVisible(true);
    }//GEN-LAST:event_btnUpdateAlienActionPerformed

    private void txtAgentPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgentPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgentPhoneActionPerformed

    private void jAgentIDStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jAgentIDStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jAgentIDStateChanged

    private void txtAgentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgentNameActionPerformed

    private void btnRegNewAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegNewAgentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegNewAgentActionPerformed

    private void txtAgentRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgentRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgentRegActionPerformed

    private void txtAgentPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgentPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgentPasswordActionPerformed

    private void jOmradeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOmradeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jOmradeBoxActionPerformed

    private void btnRegAgentBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegAgentBackActionPerformed
        //Uppdatera(hamta och populera data på nytt så den nya agenten
        //visas i homePanel)
        
        //Visa panel
        panelHome.setVisible(true);
        panelLogin.setVisible(false);
        panelRegAlien.setVisible(false);
        panelRegAgent.setVisible(false);
        panelUpdateAgent.setVisible(false);
        panelUpdateAlien.setVisible(false);
    }//GEN-LAST:event_btnRegAgentBackActionPerformed

    private void btnRegAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegAgentActionPerformed
        panelHome.setVisible(false);
        panelLogin.setVisible(false);
        panelRegAgent.setVisible(true);
        panelRegAlien.setVisible(false);
        panelUpdateAgent.setVisible(false);
        panelUpdateAlien.setVisible(false);
    }//GEN-LAST:event_btnRegAgentActionPerformed

    private void btnBackToHome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToHome1ActionPerformed
        panelHome.setVisible(true);
        panelLogin.setVisible(false);
        panelRegAlien.setVisible(false);
        panelUpdateAgent.setVisible(false);
        panelRegAgent.setVisible(false);
        panelUpdateAlien.setVisible(false);
    }//GEN-LAST:event_btnBackToHome1ActionPerformed

    private void btnChangeAlienPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeAlienPasswordActionPerformed
        System.out.println("pushed alien change pass");
        jDialog1.setSize(500, 300);
        jDialog1.setVisible(true);
    }//GEN-LAST:event_btnChangeAlienPasswordActionPerformed

    private void btnLogoutAlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutAlienActionPerformed
        program.logOut();
        
        panelHome.setVisible(false);
        panelAlienHome.setVisible(false);
        panelRegAlien.setVisible(false);
        panelUpdateAgent.setVisible(false);
        panelUpdateAlien.setVisible(false);
        panelRegAgent.setVisible(false);
        panelLogin.setVisible(true);
    }//GEN-LAST:event_btnLogoutAlienActionPerformed

    private void btnShowInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowInfoActionPerformed

    private void btnRegUtrustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegUtrustActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegUtrustActionPerformed

    private void btnUpdateAlien1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateAlien1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateAlien1ActionPerformed

    private void btnRegAlien1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegAlien1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegAlien1ActionPerformed

    private void btnChangePassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassword1ActionPerformed
        jDialog1.setSize(500, 300);
        jDialog1.setVisible(true);
    }//GEN-LAST:event_btnChangePassword1ActionPerformed

    private void btnLogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout1ActionPerformed
        program.logOut();
        panelAgentHome.setVisible(false);
        panelLogin.setVisible(true);
    }//GEN-LAST:event_btnLogout1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        jDialog1.setEnabled(false);
        jDialog1.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void updateAgent(String agentName)
    {
        //Hämta lite värden här för agent by namn
        
        //Visa panel
        panelHome.setVisible(false);
        panelLogin.setVisible(false);
        panelRegAgent.setVisible(false);
        panelRegAlien.setVisible(false);
        panelUpdateAgent.setVisible(true);
        panelUpdateAlien.setVisible(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            MainApp m;
            try {
                m = new MainApp();
                m.panelHome.setVisible(false);
                m.panelAlienHome.setVisible(false);
                m.panelAgentHome.setVisible(false);
                m.panelRegAlien.setVisible(false);
                m.panelUpdateAgent.setVisible(false);
                m.panelUpdateAlien.setVisible(false);
                m.panelRegAgent.setVisible(false);
                m.panelLogin.setVisible(true);             
                m.setVisible(true);
            
            } catch (InfException ex) {
                Logger.getLogger(MainApp.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ansvLabel;
    private javax.swing.JButton bRegistrera;
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBackToHome;
    private javax.swing.JButton btnBackToHome1;
    private javax.swing.JButton btnChangeAlienPassword;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnChangePassword1;
    private javax.swing.JButton btnDeleteAgent;
    private javax.swing.JButton btnDeleteAlien;
    private javax.swing.JButton btnDeleteUtrustning;
    private javax.swing.JButton btnDeleteUtrustning1;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnLogout1;
    private javax.swing.JButton btnLogoutAlien;
    private javax.swing.JButton btnRegAgent;
    private javax.swing.JButton btnRegAgentBack;
    private javax.swing.JButton btnRegAlien;
    private javax.swing.JButton btnRegAlien1;
    private javax.swing.JButton btnRegNewAgent;
    private javax.swing.JButton btnRegUtrust;
    private javax.swing.JButton btnShowInfo;
    private javax.swing.JButton btnUpdateAgent;
    private javax.swing.JButton btnUpdateAlien;
    private javax.swing.JButton btnUpdateAlien1;
    private javax.swing.JTextField datumField;
    private javax.swing.JLabel datumLabel;
    private javax.swing.JLabel datumLabel1;
    private javax.swing.JLabel harRegRubrik;
    private javax.swing.JLabel harRegRubrik1;
    private javax.swing.JSpinner jAgentID;
    private javax.swing.JSpinner jAlienID;
    private javax.swing.JComboBox<String> jAnsvarigBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> jOmradeBox;
    private javax.swing.JComboBox<String> jPlatsBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblAgentName;
    private javax.swing.JLabel lblAgentPhone;
    private javax.swing.JLabel lblAgentPhone1;
    private javax.swing.JLabel lblAgentPhone2;
    private javax.swing.JLabel lblAlien;
    private javax.swing.JLabel lblAlien1;
    private javax.swing.JLabel lblAlien2;
    private javax.swing.JLabel lblAlien3;
    private javax.swing.JLabel lblAlien4;
    private javax.swing.JLabel lblAlien5;
    private javax.swing.JLabel lblAlien6;
    private javax.swing.JLabel lblAlien7;
    private javax.swing.JLabel lblAlien8;
    private javax.swing.JLabel lblAlienAgentValue;
    private javax.swing.JLabel lblNewPass;
    private javax.swing.JLabel lblOmrade;
    private javax.swing.JLabel lblUpdateAgent;
    private javax.swing.JLabel lblUpdateAlien;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUser1;
    private javax.swing.JLabel lblUserAlien;
    private javax.swing.JLabel lblUtrustning;
    private javax.swing.JLabel lblUtrustning1;
    private javax.swing.JList<String> listAgents;
    private javax.swing.JList<String> listAliens;
    private javax.swing.JList<String> listAliens1;
    private javax.swing.JList<String> listAliens2;
    private javax.swing.JList<String> listAliens3;
    private javax.swing.JList<String> listUtrustning;
    private javax.swing.JList<String> listUtrustning1;
    private javax.swing.JTextField losenField;
    private javax.swing.JLabel losenLabel;
    private javax.swing.JLabel losenLabel1;
    private javax.swing.JTextField namnField;
    private javax.swing.JLabel namnLabel;
    private javax.swing.JLabel namnLabel1;
    private javax.swing.JPanel panelAgentHome;
    private javax.swing.JPanel panelAlienHome;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelRegAgent;
    private javax.swing.JPanel panelRegAlien;
    private javax.swing.JPanel panelUpdateAgent;
    private javax.swing.JPanel panelUpdateAlien;
    private javax.swing.JLabel platsLabel;
    private javax.swing.JLabel platsLabel1;
    private javax.swing.JLabel regAliRubrik;
    private javax.swing.JLabel regAliRubrik1;
    private javax.swing.JScrollPane scrollPaneAgents;
    private javax.swing.JScrollPane scrollPaneAliens;
    private javax.swing.JScrollPane scrollPaneAliens1;
    private javax.swing.JScrollPane scrollPaneAliens2;
    private javax.swing.JScrollPane scrollPaneAliens3;
    private javax.swing.JScrollPane scrollPaneUtrustning;
    private javax.swing.JScrollPane scrollPaneUtrustning1;
    private javax.swing.JLabel teleLabel;
    private javax.swing.JLabel teleLabel1;
    private javax.swing.JTextField tfnField1;
    private javax.swing.JTextField txtAgentName;
    private javax.swing.JTextField txtAgentPassword;
    private javax.swing.JTextField txtAgentPhone;
    private javax.swing.JTextField txtAgentReg;
    private javax.swing.JTextField txtNewPass;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void showRegAlien() {
        panelHome.setVisible(false);
        panelLogin.setVisible(false);
        fyllAgenter();
        sattDatum();
        fyllPlatser();
        panelRegAlien.setVisible(true);
        
    }
}
