/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import program.Program;
import db.Database;
import java.util.logging.Level;
import java.util.logging.Logger;
import oru.inf.InfException;
import java.time.LocalDate;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.*;

/**
 *
 * @author Sara
 */
public class MainApp extends javax.swing.JFrame {

    private String datum;
    private final Program program;
    
    //Ska tas bort sen
    private static final String NAME = "mibdb";
    private static final String PORT = "3306";
    private static final String USER = "mibdba";
    private static final String PASSWORD = "mibkey";
    
    private final InfDB idb;
    //Ska tas bort sen
    
    /**
     * Creates new form MainApp
     * @throws oru.inf.InfException
     */
    public MainApp() throws InfException {
        program = new Program(new Database());
        program.printAllAgents();
        
        //Ska bort
        idb = new InfDB(NAME, PORT, USER, PASSWORD);
        //Ska bort
        
        initComponents();
        
    }
    
    private void fyllAgenter()
    {
        List<String> allAgents = program.getAllAgents();
        for(String oneAgent : allAgents){
            System.out.println(oneAgent);
            jAnsvarigBox.addItem(oneAgent);
        }
    }
    
    private void fyllPlatser()
    {
        List<String> allPlatser = program.getAllPlatser();
        for(String onePlats : allPlatser){
            System.out.println(onePlats);
            jPlatsBox.addItem(onePlats);
        }
    }
    /*
    private void fyllAnsvarigRoller() {
        try {
            int id = 1;
            String cont = idb.fetchSingle("SELECT count(namn) FROM Agent");
            int max = Integer.parseInt(cont);
            while (id <= max) {
                String namn = idb.fetchSingle("SELECT Namn FROM Agent WHERE Agent_ID=" + id);
                jAnsvarigBox.addItem(namn);
                id++;
            }
        } catch (Exception e) {
            System.out.println("Knas!");
        }
    }
    */

    //Lägger in automatiskt dagens datum i datumfältet i gränssnittet
    //Detta ska ändras så att man kan välja datum men det måste vara denna typ (YY-MM-DD)
    private void sattDatum() {
        LocalDate date = LocalDate.now();
        String datum = date.toString();
        this.datum = datum;
        datumField.setText(datum);
    }

    //Samma funktion som fyllAnsvarigRoller-metoden fast den fyller PLATS i gränssnittet
    /*private void fyllPlatser() {
        try {
            int id = 1;
            String cont = idb.fetchSingle("SELECT count(Benamning) FROM Plats");
            int max = Integer.parseInt(cont);
            while (id <= max) {
                String plats = idb.fetchSingle("SELECT Benamning FROM Plats WHERE Plats_ID=" + id);
                jPlatsBox.addItem(plats);
                id++;
            }

        } catch (Exception e) {
            System.err.println("Knas");
        }
    }
    */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUpdateAgent = new javax.swing.JPanel();
        btnBackToHome = new javax.swing.JButton();
        lblUpdateAgent = new javax.swing.JLabel();
        panelLogin = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        txtPassword = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        panelHome = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();
        scrollPaneAliens = new javax.swing.JScrollPane();
        listAliens = new javax.swing.JList<>();
        lblAlien = new javax.swing.JLabel();
        btnDeleteAlien = new javax.swing.JButton();
        btnRegAlien = new javax.swing.JButton();
        btnUpdateAlien = new javax.swing.JButton();
        scrollPaneAgents = new javax.swing.JScrollPane();
        listAgents = new javax.swing.JList<>();
        lblAlien1 = new javax.swing.JLabel();
        btnRegAgent = new javax.swing.JButton();
        btnUpdateAgent = new javax.swing.JButton();
        btnDeleteAgent = new javax.swing.JButton();
        lblAgentPhone = new javax.swing.JLabel();
        lblAgentName = new javax.swing.JLabel();
        lblAgentPhone1 = new javax.swing.JLabel();
        lblAgentPhone2 = new javax.swing.JLabel();
        scrollPaneUtrustning = new javax.swing.JScrollPane();
        listUtrustning = new javax.swing.JList<>();
        lblUtrustning = new javax.swing.JLabel();
        btnDeleteUtrustning = new javax.swing.JButton();
        panelRegAlien = new javax.swing.JPanel();
        datumLabel = new javax.swing.JLabel();
        namnLabel = new javax.swing.JLabel();
        ansvLabel = new javax.swing.JLabel();
        tfnField1 = new javax.swing.JTextField();
        jAlienID = new javax.swing.JSpinner();
        namnField = new javax.swing.JTextField();
        teleLabel = new javax.swing.JLabel();
        jPlatsBox = new javax.swing.JComboBox<>();
        harRegRubrik = new javax.swing.JLabel();
        platsLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bRegistrera = new javax.swing.JButton();
        datumField = new javax.swing.JTextField();
        losenField = new javax.swing.JTextField();
        losenLabel = new javax.swing.JLabel();
        jAnsvarigBox = new javax.swing.JComboBox<>();
        regAliRubrik = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));
        setSize(new java.awt.Dimension(600, 400));

        panelUpdateAgent.setPreferredSize(new java.awt.Dimension(600, 400));

        btnBackToHome.setText("Tillbaka");
        btnBackToHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToHomeActionPerformed(evt);
            }
        });

        lblUpdateAgent.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUpdateAgent.setText("Ändra Agent");

        javax.swing.GroupLayout panelUpdateAgentLayout = new javax.swing.GroupLayout(panelUpdateAgent);
        panelUpdateAgent.setLayout(panelUpdateAgentLayout);
        panelUpdateAgentLayout.setHorizontalGroup(
            panelUpdateAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateAgentLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnBackToHome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUpdateAgentLayout.createSequentialGroup()
                .addContainerGap(259, Short.MAX_VALUE)
                .addComponent(lblUpdateAgent)
                .addGap(240, 240, 240))
        );
        panelUpdateAgentLayout.setVerticalGroup(
            panelUpdateAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUpdateAgentLayout.createSequentialGroup()
                .addComponent(lblUpdateAgent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 313, Short.MAX_VALUE)
                .addComponent(btnBackToHome)
                .addGap(22, 22, 22))
        );

        panelLogin.setPreferredSize(new java.awt.Dimension(600, 400));
        panelLogin.setRequestFocusEnabled(false);

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginLayout.createSequentialGroup()
                        .addComponent(btnLogin)
                        .addGap(30, 30, 30)))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnLogin)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        lblUser.setText("hello");

        btnLogout.setText("Logga ut");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnChangePassword.setText("Ändra lösenord");
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });

        listAliens.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollPaneAliens.setViewportView(listAliens);

        lblAlien.setText("Aliens");

        btnDeleteAlien.setText("Ta bort");

        btnRegAlien.setText("Registrera");
        btnRegAlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegAlienActionPerformed(evt);
            }
        });

        btnUpdateAlien.setText("Ändra");

        listAgents.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollPaneAgents.setViewportView(listAgents);

        lblAlien1.setText("Agenter");

        btnRegAgent.setText("Registrera");

        btnUpdateAgent.setText("Ändra");
        btnUpdateAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateAgentActionPerformed(evt);
            }
        });

        btnDeleteAgent.setText("Ta bort");

        lblAgentPhone.setText("Telefon");

        lblAgentName.setText("Namn");

        lblAgentPhone1.setText("Datum");

        lblAgentPhone2.setText("Område");

        listUtrustning.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollPaneUtrustning.setViewportView(listUtrustning);

        lblUtrustning.setText("Utrustning");

        btnDeleteUtrustning.setText("Ta bort");

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHomeLayout.createSequentialGroup()
                        .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(scrollPaneAliens, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollPaneUtrustning, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelHomeLayout.createSequentialGroup()
                                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblUtrustning)
                                    .addGroup(panelHomeLayout.createSequentialGroup()
                                        .addComponent(btnDeleteAlien)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnUpdateAlien)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRegAlien)))
                        .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelHomeLayout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(scrollPaneAgents, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHomeLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAgentPhone)
                                    .addGroup(panelHomeLayout.createSequentialGroup()
                                        .addComponent(btnDeleteAgent)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnUpdateAgent)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRegAgent))
                                    .addComponent(lblAgentName)
                                    .addComponent(lblAgentPhone1)
                                    .addComponent(lblAgentPhone2))))
                        .addContainerGap())
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelHomeLayout.createSequentialGroup()
                                .addComponent(btnLogout)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnChangePassword))
                            .addComponent(btnDeleteUtrustning))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblUser)
                        .addGap(39, 39, 39))))
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(lblAlien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAlien1)
                .addGap(108, 108, 108))
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAlien)
                    .addComponent(lblAlien1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollPaneAliens, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollPaneAgents, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteAlien)
                    .addComponent(btnRegAlien)
                    .addComponent(btnUpdateAlien)
                    .addComponent(btnRegAgent)
                    .addComponent(btnDeleteAgent)
                    .addComponent(btnUpdateAgent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAgentName)
                    .addComponent(lblUtrustning, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addComponent(lblAgentPhone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAgentPhone1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAgentPhone2))
                    .addComponent(scrollPaneUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteUtrustning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout)
                    .addComponent(lblUser)
                    .addComponent(btnChangePassword))
                .addGap(7, 7, 7))
        );

        datumLabel.setText("Datum:");

        namnLabel.setText("Namn:");

        ansvLabel.setText("Ansvarig:");

        tfnField1.setColumns(7);
        tfnField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnField1ActionPerformed(evt);
            }
        });

        jAlienID.setToolTipText("ID får inte vara identiskt med ett annat Alien_ID i databasen");
        jAlienID.setValue(4);
        jAlienID.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jAlienIDStateChanged(evt);
            }
        });

        namnField.setColumns(7);
        namnField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namnFieldActionPerformed(evt);
            }
        });

        teleLabel.setText("Telefon");

        platsLabel.setText("Plats:");

        jLabel1.setText("Alien_ID");

        bRegistrera.setText("Registrera");
        bRegistrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistreraActionPerformed(evt);
            }
        });

        datumField.setColumns(7);
        datumField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datumFieldActionPerformed(evt);
            }
        });

        losenField.setColumns(7);
        losenField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                losenFieldActionPerformed(evt);
            }
        });

        losenLabel.setText("Lösenord:");

        jAnsvarigBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAnsvarigBoxActionPerformed(evt);
            }
        });

        regAliRubrik.setFont(new java.awt.Font("Cambay Devanagari", 1, 24)); // NOI18N
        regAliRubrik.setText("Registrera alien");

        jButton1.setText("Tillbaka");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRegAlienLayout = new javax.swing.GroupLayout(panelRegAlien);
        panelRegAlien.setLayout(panelRegAlienLayout);
        panelRegAlienLayout.setHorizontalGroup(
            panelRegAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegAlienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRegAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegAlienLayout.createSequentialGroup()
                        .addComponent(jPlatsBox, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelRegAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRegAlienLayout.createSequentialGroup()
                                .addComponent(losenField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jAnsvarigBox, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bRegistrera, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelRegAlienLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addGroup(panelRegAlienLayout.createSequentialGroup()
                        .addGroup(panelRegAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelRegAlienLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(panelRegAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(datumLabel)
                                    .addComponent(platsLabel))
                                .addGap(71, 71, 71))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegAlienLayout.createSequentialGroup()
                                .addGroup(panelRegAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jAlienID, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(datumField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)))
                        .addGroup(panelRegAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegAlienLayout.createSequentialGroup()
                                .addComponent(namnLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelRegAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ansvLabel)
                                    .addComponent(teleLabel)
                                    .addComponent(tfnField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegAlienLayout.createSequentialGroup()
                                .addGroup(panelRegAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namnField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(losenLabel))
                                .addGap(112, 112, 112))))
                    .addGroup(panelRegAlienLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(regAliRubrik))
                    .addGroup(panelRegAlienLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(harRegRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        panelRegAlienLayout.setVerticalGroup(
            panelRegAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegAlienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(regAliRubrik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAlienID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datumLabel)
                    .addComponent(namnLabel)
                    .addComponent(teleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfnField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(platsLabel)
                    .addComponent(losenLabel)
                    .addComponent(ansvLabel))
                .addGap(4, 4, 4)
                .addGroup(panelRegAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(losenField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAnsvarigBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPlatsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bRegistrera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(harRegRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelRegAlien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(250, 250, 250)
                    .addComponent(panelUpdateAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(250, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelRegAlien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(150, 150, 150)
                    .addComponent(panelUpdateAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(150, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        Integer userId = Integer.valueOf(txtUsername.getText());
        String password = txtPassword.getText();
        
        program.logIn(userId, password);
        
        if(!program.isLoggedIn())
        {
            System.out.println("Could not login!");
            return;
        }
        
        if(program.isLoggedInAsAgent() && program.isAdmin())
        {
            showHome();
        }
        else if(program.isLoggedInAsAgent())
        {
            //showAgentHome()
        }
        else if(program.isLoggedInAsAlien())
        {
            //showAlienHome();
        }
        else
        {
            //Not logged in at all show error?
        }
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void showHome()
    {
        //Disable all other panels
        panelLogin.setVisible(false);
        
        //Show home panel
        lblUser.setText(program.getUserName());
        panelHome.setVisible(true);
    }
    
    private void showLogin()
    {
        panelHome.setVisible(false);
        panelLogin.setVisible(true);
    }
    
    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        program.logOut();
        showLogin();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void datumFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datumFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datumFieldActionPerformed

    private void namnFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namnFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namnFieldActionPerformed

    private void losenFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_losenFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_losenFieldActionPerformed

    private void tfnField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnField1ActionPerformed

    private void bRegistreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistreraActionPerformed
        // TODO add your handling code here:
        try {
            //Hämtar valt plats ID
            String cont = jPlatsBox.getSelectedItem().toString();
            String platsid = idb.fetchSingle("SELECT Plats_ID FROM Plats WHERE Benamning='" + cont + "'");
            //Omvandlar variabeln platsid till en int
            int plats = Integer.parseInt(platsid);
            //En "check" så att rätt värde visas
            System.out.println("Plats: " + plats);

            //Hämtar inmatat Alien ID
            String cont2 = jAlienID.getValue().toString();
            int aid = Integer.parseInt(cont2);
            System.out.println("Alien ID: " + aid);

            //Hämtar inmatat ansvarig_ID (DATATYPEN MÅSTE VARA AV INT DÄR DATABASENS TYPER ÄR INT)
            String ansvarig = jAnsvarigBox.getSelectedItem().toString();
            String ans1 = idb.fetchSingle("SELECT Agent_ID FROM Agent WHERE Namn ='" + ansvarig + "'");
            int ans = Integer.parseInt(ans1);
            System.out.println("Ansvarig :" + ans);

            //Hämtar datum
            this.datum = datumField.getText();
            System.out.println("Datum: " + datum);

            //Hämtar inmatat lösenord
            String losenord = losenField.getText();
            System.out.println("Lösenord: " + losenord);

            //Hämtar inmatat namn
            String namn = namnField.getText();
            System.out.println("Namn: " + namn);

            //Hämtar telefon
            String telefon = tfnField1.getText();

            //Hämtar alla variabler och lägger till Alien
            try {

                //Kollar så att samtliga rader är inmatade annars error
                if(losenord.isEmpty() || namn.isEmpty() || telefon.isEmpty()){
                    JOptionPane.showMessageDialog(null, "Samtliga fält måste vara ifyllda!");
                }
                else{
                    //Sätter in samtliga värden i databasen och reggar en ny alien
                    idb.insert("INSERT INTO Alien (Alien_ID, Registreringsdatum, Losenord, Namn, Telefon, Plats, Ansvarig_Agent) VALUES ('"
                        + aid + "','"
                        + datum + "','"
                        + losenord + "','"
                        + namn + "','"
                        + telefon + "','"
                        + plats + "','"
                        + ans + "')");
                    //Printas ut under button att alien har reggats
                    harRegRubrik.setText(namn + " har registrerats!");
                }

            } catch (InfException e) {
                JOptionPane.showMessageDialog(null, "Nånting blev fel. Kanske Alien_ID redan finns i databasen?");
            }

        } catch (InfException e) {
            System.out.println("Knas" + e.getMessage());
        }
    }//GEN-LAST:event_bRegistreraActionPerformed

    private void jAnsvarigBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAnsvarigBoxActionPerformed
        // TODO add your handling code here¨
    }//GEN-LAST:event_jAnsvarigBoxActionPerformed

    private void jAlienIDStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jAlienIDStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jAlienIDStateChanged

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void btnRegAlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegAlienActionPerformed
        panelHome.setVisible(false);
        panelLogin.setVisible(false);
        panelRegAlien.setVisible(true);
        panelUpdateAgent.setVisible(false);
    }//GEN-LAST:event_btnRegAlienActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        panelHome.setVisible(true);
        panelLogin.setVisible(false);
        panelRegAlien.setVisible(false);
        panelUpdateAgent.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBackToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToHomeActionPerformed
        panelHome.setVisible(true);
        panelLogin.setVisible(false);
        panelRegAlien.setVisible(false);
        panelUpdateAgent.setVisible(false);
    }//GEN-LAST:event_btnBackToHomeActionPerformed

    private void btnUpdateAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateAgentActionPerformed
        if(listAgents.getSelectedValue() == null)
        {
            //Ingen agent vald
            return;
        }
        updateAgent(listAgents.getSelectedValue());
        
    }//GEN-LAST:event_btnUpdateAgentActionPerformed

    private void updateAgent(String agentName)
    {
        //Hämta lite värden här för agent by namn
        
        //Visa panel
        panelHome.setVisible(false);
        panelLogin.setVisible(false);
        panelRegAlien.setVisible(false);
        panelUpdateAgent.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            MainApp m;
            try {
                m = new MainApp();
                m.panelHome.setVisible(false);
                m.panelRegAlien.setVisible(false);
                m.panelUpdateAgent.setVisible(false);
                m.panelLogin.setVisible(true);             
                m.setVisible(true);
            
            } catch (InfException ex) {
                Logger.getLogger(MainApp.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ansvLabel;
    private javax.swing.JButton bRegistrera;
    private javax.swing.JButton btnBackToHome;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnDeleteAgent;
    private javax.swing.JButton btnDeleteAlien;
    private javax.swing.JButton btnDeleteUtrustning;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRegAgent;
    private javax.swing.JButton btnRegAlien;
    private javax.swing.JButton btnUpdateAgent;
    private javax.swing.JButton btnUpdateAlien;
    private javax.swing.JTextField datumField;
    private javax.swing.JLabel datumLabel;
    private javax.swing.JLabel harRegRubrik;
    private javax.swing.JSpinner jAlienID;
    private javax.swing.JComboBox<String> jAnsvarigBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> jPlatsBox;
    private javax.swing.JLabel lblAgentName;
    private javax.swing.JLabel lblAgentPhone;
    private javax.swing.JLabel lblAgentPhone1;
    private javax.swing.JLabel lblAgentPhone2;
    private javax.swing.JLabel lblAlien;
    private javax.swing.JLabel lblAlien1;
    private javax.swing.JLabel lblUpdateAgent;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUtrustning;
    private javax.swing.JList<String> listAgents;
    private javax.swing.JList<String> listAliens;
    private javax.swing.JList<String> listUtrustning;
    private javax.swing.JTextField losenField;
    private javax.swing.JLabel losenLabel;
    private javax.swing.JTextField namnField;
    private javax.swing.JLabel namnLabel;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelRegAlien;
    private javax.swing.JPanel panelUpdateAgent;
    private javax.swing.JLabel platsLabel;
    private javax.swing.JLabel regAliRubrik;
    private javax.swing.JScrollPane scrollPaneAgents;
    private javax.swing.JScrollPane scrollPaneAliens;
    private javax.swing.JScrollPane scrollPaneUtrustning;
    private javax.swing.JLabel teleLabel;
    private javax.swing.JTextField tfnField1;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void showRegAlien() {
        panelHome.setVisible(false);
        panelLogin.setVisible(false);
        fyllAgenter();
        sattDatum();
        fyllPlatser();
        panelRegAlien.setVisible(true);
        
    }
}
